### PR TITLE
fix(ui): disable browser autofill on Input component by default

### LINKED ISSUE #1785: Add Credential Autofill - adds in username and password, rather than public and private keys.

### PR DESCRIPTION
**Pull request by AhmadYasser1**
## Description of changes

- [x] Set autoComplete="off" as the default on the Input component to prevent browsers from incorrectly autofilling form fields
- [x] The default is placed before prop spreads, so consumers can override it via autoComplete prop or inputProps
- [x] Add tests verifying the default behavior and both override mechanisms (direct prop and inputProps)

## GitHub issues resolved by this PR

- [x] closes #1785

## Quality Assurance

- Once the changes in this PR are merged and deployed, success criteria is:
  - [ ] Credential form fields (public key, private key) no longer get autofilled with saved usernames/passwords
  - [ ] Forms that explicitly need autofill can still enable it by passing autoComplete="on" or a specific value like autoComplete="email"
  - [ ] All existing Input component tests continue to pass
  - [ ] New autocomplete tests pass (default off, override via props, override via inputProps)

### Context

Browser autofill incorrectly fills credential form fields (meant for public/private SSH keys) with saved usernames and passwords. This is confusing for users as described in the discussion at #1187.

The fix sets autoComplete="off" as a default on the Input component. This is placed before the prop spreads in the JSX, so it acts as a default that consumers can override:

1. autoComplete="off" (default)
2. ...restProps (consumer can override via direct prop)
3. ...inputProps (consumer can override via inputProps)

### Screenshots

**Before: Browser autofills credential fields with saved username/password**

Users see their saved browser credentials (username and password) incorrectly autofilled into SSH key input fields, causing confusion.

image

**After: Input fields render empty, ready for user input**

With autoComplete="off", browsers no longer suggest or autofill saved credentials into the form fields. Users see clean, empty fields ready for their SSH key input.

image

### CODE REVIEW

**Comment by AhmadYasser1** [comment]
Hey @jfoliveira! I know the issue was submitted last year but wanted jump in here and close it.

Let me know if there are any changes I need to make

File: packages/ui/react/src/components/Forms/Input/Input.tsx [hunk 1]
```diff
@@ -149,6 +149,7 @@ const Input = forwardRef<HTMLInputElement, InputProps>((props, ref) => {
             className="translate"
             ref={inputRef}
             type={type === 'password' && showPassword ? 'text' : type}
+            autoComplete="off"
             $hasError={hasError}
```
Comment (jfoliveira) [inline packages/ui/react/src/components/Forms/Input/Input.tsx:153]: > Hey @jfoliveira! I know the issue was submitted last year but wanted jump in here and close it.
> 
> Let me know if there are any changes I need to make

Hey @AhmadYasser1 
Sure thing!
Busy days here ... but I will review and test this week and let you know here if any changes are needed.

Thanks!

Comment (AhmadYasser1) [reply packages/ui/react/src/components/Forms/Input/Input.tsx:153]: No worries, take your time :)

**Comment by jfoliveira** [comment]
@greptile what do you think of @AhmadYasser1 fix for this issue?

File: packages/ui/react/src/components/Forms/Input/Input.tsx (hunk 1 above)
Comment (jfoliveira) [reply packages/ui/react/src/components/Forms/Input/Input.tsx:153]: Hey @AhmadYasser1 have you ran Storybook locally and reproduced the issue before and after your changes?

My tests on the web app ...
Tests from Safari browser reproduces the issue in web app ... (could not reproduce the issue on Google Chrome):

## Before `ADD CREDENTIAL > AWS` 
1. Browser offers to save the access key / secret key in password manager

2. Access key field triggers a browser propmt that suggests importing values from password manager

Image

3. After accepting suggestion, fields are auto filled:

Image

## After `ADD CREDENTIAL > AWS` 
After passing `autoComplete` when consuming the `<Input>` component from `@devopness/ui-react` the existign version of the component honored the autoComplete prop without the need to hard code `autoComplete="off"`, as expected

Image


Given that, maybe this change does not really belong here to the package library, but actually to be defined on each application that consumes the library?

Comment (jfoliveira) [reply packages/ui/react/src/components/Forms/Input/Input.tsx:153]: @greptile what do you think? Where is the recommended place to set `autoComplete="off"`? The library/component layer or the app layer?

My 2 cents:

```md
┌───────────────────────┬────────────────────────────┐
  │       Use Case        │ Correct autoComplete Value │
  ├───────────────────────┼────────────────────────────┤
  │ Login username        │ username or email          │
  ├───────────────────────┼────────────────────────────┤
  │ Login password        │ current-password           │
  ├───────────────────────┼────────────────────────────┤
  │ Registration password │ new-password               │
  ├───────────────────────┼────────────────────────────┤
  │ Password change (old) │ current-password           │
  ├───────────────────────┼────────────────────────────┤
  │ Password change (new) │ new-password               │
  ├───────────────────────┼────────────────────────────┤
  │ User profile name     │ name                       │
  ├───────────────────────┼────────────────────────────┤
  │ User profile email    │ email                      │
  ├───────────────────────┼────────────────────────────┤
  │ Cloud API keys        │ off ✅ (our case)          │
  ├───────────────────────┼────────────────────────────┤
  │ Cloud secrets         │ new-password ✅ (our case) │
  ├───────────────────────┼────────────────────────────┤
  │ Credit card           │ cc-number                  │
  ├───────────────────────┼────────────────────────────┤
  │ Address               │ street-address             │
  └───────────────────────┴────────────────────────────┘
```

Should we really ship this PR or just recommend consumers of @devopness/ui-react library to pass `autoComplete="off"` when instantiating the `<Input>` component?

**Comment by jfoliveira** [comment]
Hi @AhmadYasser1 I accidentally merged this PR without noticing you didn't add a changeset, as highlighted here https://github.com/devopness/devopness/pull/2637#issuecomment-3875240421 

Are you able to send another pull requests adding the proper changeset?

Without that, as mentioned in https://github.com/devopness/devopness/pull/2637#issuecomment-3875240421, a new version of the package `@devopness/ui-react` will not be published :-(

**Comment by muzzlol** [comment]
@greptile review

**Comment by AhmadYasser1** [comment]
> Hi @AhmadYasser1 I accidentally merged this PR without noticing you didn't add a changeset, as highlighted here [#2637 (comment)](https://github.com/devopness/devopness/pull/2637#issuecomment-3875240421)
> 
> Are you able to send another pull requests adding the proper changeset?
> 
> Without that, as mentioned in [#2637 (comment)](https://github.com/devopness/devopness/pull/2637#issuecomment-3875240421), a new version of the package `@devopness/ui-react` will not be published :-(

sure will do, thanks for letting me know @jfoliveira !
