### PR TITLE
fix: DropdownOption.badge.color not working (#1504)

### LINKED ISSUE #1504: [Bug]: DropdownOption.badge.color not working
### Problem: What is happening?

When customizing the Dropdown option badge icon color, the color does not change

### Expected behavior

When using the options below, the badge icon color should be `blue.800` (`#2e364e`)

I want to pass the same color prop as the [Icon component](https://storybook.devopness.com/?path=/docs/primitives-icon--docs)

Adding the color prop is sufficient, but it would be nice to have access to all the Icon props when "badge.icon == true"

```json
[
  {
    "badge": {
      "icon": true,
      "name": "riTeamLine",
      "color": "blue.800"
    },
    "label": "Teams invitations"
  },
  {
    "badge": {
      "icon": true,
      "name": "aiOutlineDollarCircle",
      "color": "blue.800"
    },
    "label": "Billing & plans"
  },
  {
    "badge": {
      "icon": true,
      "name": "logout",
      "color": "blue.800"
    },
    "label": "Sign out"
  }
]
```

### Steps to reproduce

1. Go to https://storybook.devopness.com/?path=/story/primitives-dropdown--primary
1. Replace the options JSON with [1]
    1. I expected the icon color to match the option text color
    1. The result is the icon color does not change

[1] 

```json
[
  {
    "badge": {
      "icon": true,
      "name": "riTeamLine",
      "color": "blue.800"
    },
    "label": "Teams invitations"
  },
  {
    "badge": {
      "icon": true,
      "name": "aiOutlineDollarCircle",
      "color": "blue.800"
    },
    "label": "Billing & plans"
  },
  {
    "badge": {
      "icon": true,
      "name": "logout",
      "color": "blue.800"
    },
    "label": "Sign out"
  }
]
```

### Which Devopness module(s) are the source of the bug?

UI - Design System / React components

### Package Version

_No response_

### Reproduction link

_No response_

### Additional details

Image

### PR DESCRIPTION
**Pull request by sagarpatketdot**
## Description of changes

- [ ] allows customizing dropdown option badge icon color
- [ ] adds test case to check for dropdown option badge color change

## GitHub issues resolved by this PR

- [ ] closes #1504

## Quality Assurance

- Once the changes in this PR are merged and deployed, success criteria is:
Use storyboard to verify customizing dropdown option badge icon color. Instructions are mentioned in #1504.

### CODE REVIEW

File: packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -350,6 +350,7 @@ const Dropdown = ({
                           >
                             {option.badge.icon ? (
                               <Icon
+                                color={option.badge.color as Color}
```
Comment (thlmenezes) [inline packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx:353]: @sagarpatketdot instead of using a type assertion here, could you update the `DropdownOptionIcon`?

The current approach will attempt to use the CSS property color prop as a token for our Design System Color, which may lead to unexpected results, because of the code below

https://github.com/devopness/devopness/blob/f86af9c21e974062f0cbb66926bcd524db41a5fb/packages/ui/react/src/components/Primitives/Icon/Icon.tsx#L53

My suggestion is:

1. Update `DropdownOptionIcon`
2. Update the Icon badge accordingly

```tsx
type DropdownOptionIcon = Unwrap<
  IconProps & Pick<React.CSSProperties, 'backgroundColor'>
> & { icon: true }
// ...
                            {option.badge.icon ? (
                              <Icon
                                {...option.badge}
                                size={option.badge.size ?? 12}
                              />
                            ) : (
// ...
```

**Comment by sagarpatketdot** [comment]
I have read the CLA document and I hereby sign the CLA

**Comment by sagarpatketdot** [comment]
recheck

**Comment by thlmenezes** [comment]
recheck

**Review by thlmenezes — CHANGES_REQUESTED** [review]

File: packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (sagarpatketdot) [reply packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx:353]: I have updated DropdownOptionIcon type as requested to remove type assertion.

File: packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -28,8 +28,8 @@ const DEFAULT_BUTTON_ICON_SIZE = 10
 const DEFAULT_ICON_MARGIN = 10
 
 type DropdownOptionIcon = Unwrap<
-  Partial<Pick<IconProps, 'name' | 'size'>> &
-    Pick<React.CSSProperties, 'backgroundColor' | 'color'>
+  IconProps &
+  Pick<React.CSSProperties, 'backgroundColor' | 'color'>
```
Comment (thlmenezes) [inline packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx:32]:
```suggestion
  IconProps &
  Pick<React.CSSProperties, 'backgroundColor'>
```

File: packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx [hunk 3]
```diff
@@ -350,6 +350,7 @@ const Dropdown = ({
                           >
                             {option.badge.icon ? (
                               <Icon
+                                color={option.badge.color}
                                 name={option.badge.name}
```
Comment (thlmenezes) [inline packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx:354]:
```suggestion
                                {...option.badge}
```

**Review by thlmenezes — DISMISSED** [review]
@sagarpatketdot nice work, could you apply the following changes below?

File: packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx (hunk 3 above)
Comment (sagarpatketdot) [reply packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx:354]: Certainly.

Comment (thlmenezes) [reply packages/ui/react/src/components/Primitives/Dropdown/Dropdown.tsx:354]: @sagarpatketdot can you apply the suggestion?

Also, the current code is failing CI - lint, so remember to apply prettier to the files

https://github.com/devopness/devopness/actions/runs/14411401440/job/40450967641?pr=1566

image

**Review by jfoliveira — APPROVED** [review]
